# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com
  ropensci: http://packages.ropensci.com
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
